volumes:

  production_traefik: {}
  production_django_media: {}
  production_redis_data: {}
  
services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: projects_production_django
    volumes:
      - production_django_media:/app/projects/media
    depends_on:
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: projects_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:8000:8000'
      - '0.0.0.0:5555:5555'

  redis:
    image: docker.io/redis:6
    
    volumes:
      - production_redis_data:/data
    

  celeryworker:
    <<: *django
    image: projects_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: projects_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: projects_production_flower
    command: /start-flower

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: projects_production_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
