# Generated by Django 4.2.4 on 2023-09-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasicSetup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("app_name", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="logos/")),
                ("favicon", models.ImageField(upload_to="favicons/")),
                ("is_setup_complete", models.BooleanField(default=False)),
            ],
        ),
    ]
