# Generated by Django 4.0.8 on 2023-09-25 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0002_delete_basicsetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('criteria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DropDownFieldValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=50)),
                ('fieldvalue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.IntegerField()),
                ('is_default', models.BooleanField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.criteria')),
            ],
        ),
    ]
