# Generated by Django 5.0.9 on 2024-10-13 17:17

import uuid
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    for row in Document.objects.all():
        row.new_id = uuid.uuid4()
        row.save(update_fields=['new_id'])


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="new_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(gen_uuid),
        migrations.RemoveField(
            model_name="document",
            name="id",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="new_id",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
