# Generated by Django 4.0.8 on 2023-09-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installer', '0002_installedapp_author_installedapp_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedapp',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='installedapp',
            name='category',
            field=models.CharField(max_length=200, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='installedapp',
            name='other',
            field=models.JSONField(null=True, verbose_name='Others'),
        ),
        migrations.AlterField(
            model_name='installedapp',
            name='version',
            field=models.CharField(max_length=100, verbose_name='Version'),
        ),
    ]
