# Generated by Django 5.0.9 on 2024-10-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gitea_token",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Gitea Token"
            ),
        ),
    ]
