# Generated by Django 5.0.9 on 2024-10-14 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repositories",
                to="project.project",
            ),
        ),
    ]
