log:
  level: DEBUG

entryPoints:
  web:
    # http
    address: ':8000'

  flower:
    address: ':5555'

http:
  routers:
    web-router:
      rule: 'Host(`localhost`)'  # Changed from `localhost.com` to `localhost`
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django
      tls: false

    flower-router:
      rule: 'Host(`localhost`)'  # Changed from `localhost.com` to `localhost`
      entryPoints:
        - flower
      service: flower
      tls: false

    web-media-router:
      rule: 'Host(`localhost`) && PathPrefix(`/media/`)'  # Changed from `localhost.com` to `localhost`
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django-media
      tls: false

  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
